CREATE TABLE IF NOT EXISTS Product (
	ProductID CHAR(36) PRIMARY KEY,
	CompanyID CHAR(36) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(255),
	Price DECIMAL(18,2) NOT NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
	CreatedAt DATETIME NOT NULL
);