CREATE TABLE IF NOT EXISTS CompanySettings (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    CompanyId CHAR(36) NOT NULL,
    BillingPlan VARCHAR(50) NOT NULL,
    ModulesEnabled TEXT NOT NULL,
    IsDisabled BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;