CREATE TABLE IF NOT EXISTS CompanyUserRoles (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    CompanyUserId CHAR(36) NOT NULL,
    RoleName VARCHAR(50) NOT NULL,
    AssignedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;