<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Sales.Application\Sales.Application.csproj" />
    <ProjectReference Include="..\Sales.Contracts\Sales.Contracts.csproj" />
    <ProjectReference Include="..\..\Platform\Platform.Web\Platform.Web.csproj" />
    <ProjectReference Include="..\..\CRM\CRM.Application\CRM.Application.csproj" />
    <ProjectReference Include="..\..\Inventory\Inventory.Application\Inventory.Application.csproj" />
    <ProjectReference Include="..\..\..\shared\BusinessAsUsual.Shared.UI\BusinessAsUsual.Shared.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.7.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
