namespace Platform.Application.DTOs.Import;

/// <summary>
/// Represents a database table schema
/// </summary>
public class TableSchema
{
    public string TableName { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public List<ColumnSchema> Columns { get; set; } = new();
    public List<ForeignKeySchema> ForeignKeys { get; set; } = new();
}

/// <summary>
/// Represents a database column schema
/// </summary>
public class ColumnSchema
{
    public string ColumnName { get; set; } = string.Empty;
    public string DataType { get; set; } = string.Empty;
    public bool IsNullable { get; set; }
    public bool IsPrimaryKey { get; set; }
    public bool IsForeignKey { get; set; }
    public int? MaxLength { get; set; }
    public bool IsRequired => !IsNullable && !IsAutoGenerated;
    public string? DefaultValue { get; set; }

    /// <summary>
    /// Indicates whether this column is auto-generated (e.g., Id, CreatedAt, CompanyId)
    /// and does not need to be provided in import data
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Indicates whether this column should be provided by the user during import
    /// (opposite of IsAutoGenerated, for clarity in UI)
    /// </summary>
    public bool IsUserProvided => !IsAutoGenerated;

    /// <summary>
    /// Human-readable explanation of why a column is auto-generated
    /// </summary>
    public string? AutoGenerationReason { get; set; }
}

/// <summary>
/// Represents a foreign key relationship
/// </summary>
public class ForeignKeySchema
{
    public string ColumnName { get; set; } = string.Empty;
    public string ReferencedTable { get; set; } = string.Empty;
    public string ReferencedColumn { get; set; } = string.Empty;
}
