// <auto-generated />
using System;
using BusinessAsUsual.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessAsUsual.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessDbContext))]
    partial class BusinessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyInfo", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanySetting", b =>
                {
                    b.Property<Guid>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRole", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyUserRoles");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRoleAssignment", b =>
                {
                    b.Property<Guid>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignmentID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("CompanyUserRoleAssignments");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermission", b =>
                {
                    b.Property<Guid>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("CompanyUserRolePermissions");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroup", b =>
                {
                    b.Property<Guid>("PermissionGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PermissionGroupID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyUserRolePermissionGroups");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroupAssignment", b =>
                {
                    b.Property<Guid>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionGroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AssignmentID");

                    b.HasIndex("PermissionGroupID");

                    b.HasIndex("RoleID");

                    b.ToTable("CompanyUserRolePermissionGroupAssignments");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroupAudit", b =>
                {
                    b.Property<Guid>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionGroupID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditID");

                    b.HasIndex("ChangedByUserID");

                    b.HasIndex("PermissionGroupID");

                    b.ToTable("CompanyUserRolePermissionGroupAudits");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroupMember", b =>
                {
                    b.Property<Guid>("GroupMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionGroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupMemberID");

                    b.HasIndex("PermissionGroupID");

                    b.HasIndex("PermissionID");

                    b.ToTable("CompanyUserRolePermissionGroupMembers");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionOverride", b =>
                {
                    b.Property<Guid>("OverrideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OverrideID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("UserID");

                    b.ToTable("CompanyUserRolePermissionOverrides");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionSetting", b =>
                {
                    b.Property<Guid>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingID");

                    b.HasIndex("PermissionID");

                    b.ToTable("CompanyUserRolePermissionSettings");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRoleSetting", b =>
                {
                    b.Property<Guid>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingID");

                    b.HasIndex("RoleID");

                    b.ToTable("CompanyUserRoleSettings");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserSetting", b =>
                {
                    b.Property<Guid>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SettingID");

                    b.HasIndex("UserID");

                    b.ToTable("CompanyUserSettings");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanySetting", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyInfo", "Company")
                        .WithMany("Settings")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUser", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyInfo", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRole", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyInfo", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRoleAssignment", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRole", "Role")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUser", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermission", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroup", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyInfo", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroupAssignment", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroup", "PermissionGroup")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("PermissionGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRole", "Role")
                        .WithMany("PermissionGroupAssignments")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroupAudit", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroup", "PermissionGroup")
                        .WithMany("AuditTrail")
                        .HasForeignKey("PermissionGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroupMember", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroup", "PermissionGroup")
                        .WithMany("Members")
                        .HasForeignKey("PermissionGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermission", "Permission")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionOverride", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermission", "Permission")
                        .WithMany("Overrides")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUser", "User")
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionSetting", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermission", "Permission")
                        .WithMany("Settings")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRoleSetting", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUserRole", "Role")
                        .WithMany("Settings")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserSetting", b =>
                {
                    b.HasOne("BusinessAsUsual.Domain.Entities.Company.CompanyUser", "User")
                        .WithMany("Settings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyInfo", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Settings");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUser", b =>
                {
                    b.Navigation("PermissionOverrides");

                    b.Navigation("RoleAssignments");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRole", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("PermissionGroupAssignments");

                    b.Navigation("Permissions");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermission", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("Overrides");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("BusinessAsUsual.Domain.Entities.Company.CompanyUserRolePermissionGroup", b =>
                {
                    b.Navigation("AuditTrail");

                    b.Navigation("Members");

                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
