using Microsoft.Extensions.Logging;
using Platform.Application.DTOs.Import;
using Platform.Application.Services;

namespace Platform.Infrastructure.Services;

/// <summary>
/// Implementation of column mapping service with fuzzy matching
/// </summary>
public class ColumnMappingService : IColumnMappingService
{
    private readonly ILogger<ColumnMappingService> _logger;

    public ColumnMappingService(ILogger<ColumnMappingService> logger)
    {
        _logger = logger;
    }

    public async Task<ColumnMappingAnalysis> AnalyzeAndMapColumnsAsync(
        List<string> sourceColumns,
        TableSchema targetSchema,
        ColumnMatchingOptions? options = null)
    {
        options ??= new ColumnMatchingOptions();
        var analysis = new ColumnMappingAnalysis();

        var targetColumns = targetSchema.Columns.Select(c => c.ColumnName).ToList();
        var unmappedTargets = new HashSet<string>(targetColumns);

        // Try to auto-map each source column
        foreach (var sourceColumn in sourceColumns)
        {
            var bestMatch = FindBestMatch(sourceColumn, targetColumns, options, unmappedTargets);

            if (bestMatch != null)
            {
                var targetColumn = targetSchema.Columns.First(c => c.ColumnName == bestMatch);
                analysis.Mappings.Add(new ColumnMappingDefinition
                {
                    SourceColumn = sourceColumn,
                    TargetColumn = bestMatch,
                    IsRequired = targetColumn.IsRequired
                });
                unmappedTargets.Remove(bestMatch);
            }
            else
            {
                // No good match found
                analysis.UnmappedSourceColumns.Add(sourceColumn);
            }
        }

        // Identify required target columns that weren't mapped
        // Exclude auto-generated columns as they don't need to be provided by user
        analysis.UnmappedTargetColumns = unmappedTargets
            .Where(t =>
            {
                var column = targetSchema.Columns.First(c => c.ColumnName == t);
                return column.IsRequired && !column.IsAutoGenerated;
            })
            .ToList();

        // Calculate confidence score
        analysis.ConfidenceScore = CalculateConfidenceScore(analysis, targetSchema);

        _logger.LogInformation("Column mapping analysis complete: {MappedCount} mapped, {UnmappedSourceCount} unmapped sources, {UnmappedTargetCount} unmapped required targets",
            analysis.Mappings.Count, analysis.UnmappedSourceColumns.Count, analysis.UnmappedTargetColumns.Count);

        await Task.CompletedTask; // To satisfy async signature
        return analysis;
    }

    public async Task<(bool IsValid, List<string> Errors)> ValidateMappingsAsync(
        ColumnMappingAnalysis mappings,
        TableSchema targetSchema)
    {
        var errors = new List<string>();

        // Check that all required target columns are mapped (excluding auto-generated ones)
        var requiredColumns = targetSchema.Columns
            .Where(c => c.IsRequired && !c.IsAutoGenerated)
            .Select(c => c.ColumnName)
            .ToHashSet();
        var mappedTargets = mappings.Mappings.Select(m => m.TargetColumn).ToHashSet();

        foreach (var required in requiredColumns)
        {
            if (!mappedTargets.Contains(required))
            {
                errors.Add($"Required column '{required}' is not mapped");
            }
        }

        // Check for duplicate target mappings
        var duplicates = mappings.Mappings
            .GroupBy(m => m.TargetColumn)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key);

        foreach (var duplicate in duplicates)
        {
            errors.Add($"Column '{duplicate}' is mapped multiple times");
        }

        // Validate transformations
        foreach (var mapping in mappings.Mappings.Where(m => m.Transformation != null))
        {
            // Transformation validation would go here
            // For now, just check that it exists
            if (string.IsNullOrWhiteSpace(mapping.Transformation!.TransformationType))
            {
                errors.Add($"Invalid transformation for mapping {mapping.SourceColumn} -> {mapping.TargetColumn}");
            }
        }

        await Task.CompletedTask; // To satisfy async signature
        return (errors.Count == 0, errors);
    }

    public int CalculateSimilarity(string source, string target, ColumnMatchingOptions options)
    {
        // Normalize the strings based on options
        var normalizedSource = NormalizeColumnName(source, options);
        var normalizedTarget = NormalizeColumnName(target, options);

        // Exact match
        if (normalizedSource == normalizedTarget)
        {
            return 100;
        }

        // Calculate Levenshtein distance
        var distance = LevenshteinDistance(normalizedSource, normalizedTarget);
        var maxLength = Math.Max(normalizedSource.Length, normalizedTarget.Length);

        if (maxLength == 0) return 100;

        var similarity = (1.0 - (double)distance / maxLength) * 100;

        // Boost score if one string contains the other
        if (normalizedSource.Contains(normalizedTarget) || normalizedTarget.Contains(normalizedSource))
        {
            similarity = Math.Min(100, similarity + 20);
        }

        return (int)Math.Round(similarity);
    }

    public Task SaveMappingTemplateAsync(string templateName, string tableName, ColumnMappingAnalysis mappings, string userId)
    {
        // TODO: Implement persistence to database using ColumnMapping entity
        _logger.LogInformation("Saving mapping template {TemplateName} for table {TableName} by user {UserId}",
            templateName, tableName, userId);
        return Task.CompletedTask;
    }

    public Task<ColumnMappingAnalysis?> LoadMappingTemplateAsync(string templateName, string tableName)
    {
        // TODO: Implement loading from database
        _logger.LogInformation("Loading mapping template {TemplateName} for table {TableName}",
            templateName, tableName);
        return Task.FromResult<ColumnMappingAnalysis?>(null);
    }

    private string? FindBestMatch(string sourceColumn, List<string> targetColumns, ColumnMatchingOptions options, HashSet<string> availableTargets)
    {
        string? bestMatch = null;
        int bestScore = 0;

        foreach (var targetColumn in targetColumns)
        {
            if (!availableTargets.Contains(targetColumn))
                continue; // Already mapped

            var score = CalculateSimilarity(sourceColumn, targetColumn, options);

            if (score >= options.MinimumSimilarityScore && score > bestScore)
            {
                bestScore = score;
                bestMatch = targetColumn;
            }
        }

        return bestMatch;
    }

    private string NormalizeColumnName(string columnName, ColumnMatchingOptions options)
    {
        var normalized = columnName;

        if (options.IgnoreCase)
        {
            normalized = normalized.ToLowerInvariant();
        }

        if (options.IgnoreUnderscores)
        {
            normalized = normalized.Replace("_", "");
        }

        if (options.IgnoreSpaces)
        {
            normalized = normalized.Replace(" ", "");
        }

        return normalized;
    }

    private double CalculateConfidenceScore(ColumnMappingAnalysis analysis, TableSchema targetSchema)
    {
        if (analysis.Mappings.Count == 0)
            return 0.0;

        // Factor 1: Percentage of source columns mapped
        double mappedRatio = (double)analysis.Mappings.Count / (analysis.Mappings.Count + analysis.UnmappedSourceColumns.Count);

        // Factor 2: All required target columns are mapped
        double requiredMapped = analysis.UnmappedTargetColumns.Count == 0 ? 1.0 : 0.5;

        // Factor 3: No validation errors
        double noErrors = analysis.ValidationErrors.Count == 0 ? 1.0 : 0.7;

        return (mappedRatio * 0.4) + (requiredMapped * 0.4) + (noErrors * 0.2);
    }

    private int LevenshteinDistance(string source, string target)
    {
        if (string.IsNullOrEmpty(source))
        {
            return string.IsNullOrEmpty(target) ? 0 : target.Length;
        }

        if (string.IsNullOrEmpty(target))
        {
            return source.Length;
        }

        var distance = new int[source.Length + 1, target.Length + 1];

        for (var i = 0; i <= source.Length; i++)
        {
            distance[i, 0] = i;
        }

        for (var j = 0; j <= target.Length; j++)
        {
            distance[0, j] = j;
        }

        for (var i = 1; i <= source.Length; i++)
        {
            for (var j = 1; j <= target.Length; j++)
            {
                var cost = target[j - 1] == source[i - 1] ? 0 : 1;
                distance[i, j] = Math.Min(
                    Math.Min(distance[i - 1, j] + 1, distance[i, j - 1] + 1),
                    distance[i - 1, j - 1] + cost);
            }
        }

        return distance[source.Length, target.Length];
    }
}
