using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Platform.Application.DTOs.Import;
using Platform.Application.Services;

namespace Platform.Infrastructure.Services;

/// <summary>
/// Implementation of schema introspection using EF Core metadata
/// NOTE: This service uses a registry pattern to avoid circular dependencies.
/// DbContexts must be registered via AddSchemaIntrospection extension method.
/// </summary>
public class SchemaIntrospectionService : ISchemaIntrospectionService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<SchemaIntrospectionService> _logger;
    private static readonly Dictionary<string, Type> _dbContextRegistry = new();
    private static readonly Dictionary<string, string> _entityTypeRegistry = new();

    // Define which tables are importable (whitelist approach for security)
    private static readonly HashSet<string> ImportableTables = new()
    {
        "Employee",
        "Department",
        "Customer",
        "Order",
        "Product",
        "Invoice"
    };

    public SchemaIntrospectionService(
        IServiceProvider serviceProvider,
        ILogger<SchemaIntrospectionService> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }

    /// <summary>
    /// Registers a DbContext type for schema introspection
    /// </summary>
    public static void RegisterDbContext<TContext>(params string[] tableNames) where TContext : DbContext
    {
        foreach (var tableName in tableNames)
        {
            _dbContextRegistry[tableName] = typeof(TContext);
        }
    }

    /// <summary>
    /// Registers an entity type for a table name
    /// </summary>
    public static void RegisterEntityType(string tableName, string fullTypeName)
    {
        _entityTypeRegistry[tableName] = fullTypeName;
    }

    public Task<List<string>> GetImportableTablesAsync()
    {
        // Only return tables that have been registered
        var registered = ImportableTables.Where(t => _dbContextRegistry.ContainsKey(t)).OrderBy(t => t).ToList();
        return Task.FromResult(registered);
    }

    public async Task<TableSchema?> GetTableSchemaAsync(string tableName)
    {
        try
        {
            if (!ImportableTables.Contains(tableName) || !_dbContextRegistry.ContainsKey(tableName))
            {
                _logger.LogWarning("Attempt to introspect non-registered table: {TableName}", tableName);
                return null;
            }

            var entityType = await GetEntityTypeAsync(tableName);
            if (entityType == null)
            {
                _logger.LogWarning("Could not find entity type for table: {TableName}", tableName);
                return null;
            }

            var schema = new TableSchema
            {
                TableName = tableName,
                DisplayName = FormatDisplayName(tableName)
            };

            // Extract column information
            foreach (var property in entityType.GetProperties())
            {
                var columnSchema = new ColumnSchema
                {
                    ColumnName = property.Name,
                    DataType = property.ClrType.Name,
                    IsNullable = property.IsNullable,
                    IsPrimaryKey = property.IsPrimaryKey(),
                    MaxLength = property.GetMaxLength()
                };

                // Detect auto-generated columns
                columnSchema.IsAutoGenerated = IsAutoGeneratedColumn(property, entityType);
                if (columnSchema.IsAutoGenerated)
                {
                    columnSchema.AutoGenerationReason = GetAutoGenerationReason(property, entityType);
                }

                schema.Columns.Add(columnSchema);
            }

            // Extract foreign key information
            foreach (var foreignKey in entityType.GetForeignKeys())
            {
                var fkSchema = new ForeignKeySchema
                {
                    ColumnName = foreignKey.Properties.First().Name,
                    ReferencedTable = foreignKey.PrincipalEntityType.ClrType.Name,
                    ReferencedColumn = foreignKey.PrincipalKey.Properties.First().Name
                };

                schema.ForeignKeys.Add(fkSchema);

                // Mark the column as a foreign key
                var column = schema.Columns.FirstOrDefault(c => c.ColumnName == fkSchema.ColumnName);
                if (column != null)
                {
                    column.IsForeignKey = true;
                }
            }

            return schema;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error introspecting schema for table {TableName}", tableName);
            return null;
        }
    }

    public async Task<Dictionary<string, TableSchema>> GetTableSchemasAsync(IEnumerable<string> tableNames)
    {
        var schemas = new Dictionary<string, TableSchema>();

        foreach (var tableName in tableNames)
        {
            var schema = await GetTableSchemaAsync(tableName);
            if (schema != null)
            {
                schemas[tableName] = schema;
            }
        }

        return schemas;
    }

    private async Task<IEntityType?> GetEntityTypeAsync(string tableName)
    {
        try
        {
            if (!_dbContextRegistry.TryGetValue(tableName, out var contextType) ||
                !_entityTypeRegistry.TryGetValue(tableName, out var entityTypeName))
            {
                return null;
            }

            using var scope = _serviceProvider.CreateScope();
            var context = scope.ServiceProvider.GetService(contextType) as DbContext;
            if (context == null) return null;

            return context.Model.FindEntityType(entityTypeName);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error finding entity type for {TableName}", tableName);
            return null;
        }
    }

    private static string FormatDisplayName(string tableName)
    {
        // Convert PascalCase to "Title Case" with spaces
        return System.Text.RegularExpressions.Regex.Replace(tableName, "([a-z])([A-Z])", "$1 $2");
    }

    /// <summary>
    /// Determines if a column is auto-generated and should not be provided during import
    /// </summary>
    private static bool IsAutoGeneratedColumn(IProperty property, IEntityType entityType)
    {
        var propertyName = property.Name;
        var propertyType = property.ClrType;

        // Primary key columns (typically Id)
        if (property.IsPrimaryKey() && propertyType == typeof(Guid))
        {
            return true;
        }

        // Tenant/Company context columns
        if (propertyName.Equals("CompanyId", StringComparison.OrdinalIgnoreCase) ||
            propertyName.Equals("TenantId", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        // Timestamp columns with default values
        if ((propertyName.Equals("CreatedAt", StringComparison.OrdinalIgnoreCase) ||
             propertyName.Equals("UpdatedAt", StringComparison.OrdinalIgnoreCase) ||
             propertyName.Equals("ModifiedAt", StringComparison.OrdinalIgnoreCase)) &&
            propertyType == typeof(DateTime))
        {
            return true;
        }

        // Legacy ID columns used for migration tracking
        if (propertyName.Equals("LegacyId", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        // Database-generated values (auto-increment, computed, etc.)
        if (property.ValueGenerated != Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never)
        {
            return true;
        }

        // Navigation properties and collections (not actual columns)
        if (property.IsShadowProperty() || 
            typeof(System.Collections.IEnumerable).IsAssignableFrom(propertyType) && propertyType != typeof(string))
        {
            return true;
        }

        return false;
    }

    /// <summary>
    /// Provides a human-readable reason why a column is auto-generated
    /// </summary>
    private static string GetAutoGenerationReason(IProperty property, IEntityType entityType)
    {
        var propertyName = property.Name;

        if (property.IsPrimaryKey())
            return "Primary key - auto-generated";

        if (propertyName.Equals("CompanyId", StringComparison.OrdinalIgnoreCase) ||
            propertyName.Equals("TenantId", StringComparison.OrdinalIgnoreCase))
            return "Tenant context - set automatically";

        if (propertyName.Equals("CreatedAt", StringComparison.OrdinalIgnoreCase))
            return "Timestamp - set on creation";

        if (propertyName.Equals("UpdatedAt", StringComparison.OrdinalIgnoreCase) ||
            propertyName.Equals("ModifiedAt", StringComparison.OrdinalIgnoreCase))
            return "Timestamp - set on update";

        if (propertyName.Equals("LegacyId", StringComparison.OrdinalIgnoreCase))
            return "Legacy migration tracking";

        if (property.ValueGenerated != Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never)
            return "Database-generated value";

        return "Auto-generated by system";
    }
}
