CREATE TABLE IF NOT EXISTS CompanyUserRolePermissions (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    CompanyUserRoleId CHAR(36) NOT NULL,
    PermissionKey VARCHAR(100) NOT NULL,
    IsAllowed BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;