CREATE TABLE IF NOT EXISTS CompanyUsers (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    CompanyId CHAR(36) NOT NULL,
    UserName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;