name: Generate Changelog

on:
  pull_request:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Conventional Changelog Action"
          git config user.email "conventional.changelog.action@github.com"

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        run: |
          if git rev-parse "${{ steps.get_tag.outputs.tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ steps.get_tag.outputs.tag }} already exists. Skipping release."
            exit 0
          fi

      - name: Fetch full Git history and tags
        run: git fetch --unshallow --tags

      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: CHANGELOG.md
          skip-version-file: true
          tag-prefix: v
          preset: angular
          fallback-version: 0.1.1