name: Release Orchestration

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Conventional Changelog Action"
          git config user.email "conventional.changelog.action@github.com"

      - name: Fetch full Git history and tags
        run: git fetch --unshallow --tags

      - name: Generate changelog and tag release
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: CHANGELOG.md
          skip-version-file: true
          tag-prefix: v
          preset: angular
          fallback-version: 0.1.1
          create-release: true
          release-title: "BusinessAsUsual v${{ steps.changelog.outputs.version }}"
          release-notes: true